name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Build APK with official Kivy Buildozer Action
      - name: Build APK
        uses: kivy/buildozer-action@v1
        with:
          command: buildozer -v android debug

      # 3️⃣ Upload APK artifact (download from Actions tab)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk

      # 4️⃣ Optional: Create GitHub Release with APK attached
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}