name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Install Java, Python dependencies, Buildozer
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk python3-pip unzip git build-essential
          pip install --user cython buildozer

      # 3️⃣ Download Android SDK + NDK + Build Tools
      - name: Setup Android SDK/NDK
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          yes | $HOME/Android/Sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;25.2.9519653"

      # 4️⃣ Build APK with Buildozer
      - name: Build APK
        run: |
          # Set Java path
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH

          # Add Buildozer, SDK, Build Tools, NDK to PATH
          export PATH=$PATH:$HOME/.local/bin
          export PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/latest/bin
          export PATH=$PATH:$HOME/Android/Sdk/platform-tools
          export PATH=$PATH:$HOME/Android/Sdk/build-tools/30.0.3
          export PATH=$PATH:$HOME/Android/Sdk/ndk/25.2.9519653

          # Build APK
          buildozer android debug

      # 5️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk
