name: Build Android APK

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches:
      - main           # or your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk unzip git \
                             python3-dev python3-setuptools python3-venv \
                             build-essential libssl-dev libffi-dev \
                             libgl1-mesa-dev libgles2-mesa-dev \
                             zlib1g-dev libncurses5-dev libsqlite3-dev \
                             libgdbm-dev libbz2-dev liblzma-dev

          pip install --user cython buildozer

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Android licenses
        run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses

      - name: Install Build Tools
        run: sdkmanager "build-tools;36.1.0"

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk
