name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Install Java 11, Python dependencies, and Buildozer
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk python3-pip unzip git build-essential
          pip install --user cython buildozer

      # 3️⃣ Download and set up Android SDK
      - name: Setup Android SDK
        run: |
          mkdir -p $HOME/Android/Sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/Android/Sdk/cmdline-tools
          yes | $HOME/Android/Sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --licenses
          $HOME/Android/Sdk/cmdline-tools/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;36.1.0"

      # 4️⃣ Build APK with Buildozer
      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin:$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/build-tools/36.1.0
          buildozer android debug

      # 5️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk
