name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repo
    - name: Checkout
      uses: actions/checkout@v4

    # 2️⃣ Build APK with Buildozer (stable action release)
    - name: Build with Buildozer
      id: buildozer
      uses: ArtemSBulgakov/buildozer-action@v1.2.0
      with:
        workdir: .
        buildozer_version: stable
        command: buildozer -v android debug
      env:
        USER: runner

    # 3️⃣ Upload APK artifact (accessible in Actions → Artifacts)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: faultcodes-apk
        path: ${{ steps.buildozer.outputs.filename }}

    # 4️⃣ Optional: make a GitHub Release each push to main
    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: ${{ steps.buildozer.outputs.filename }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}