name: Build Android APK

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip unzip git \
                             python3-dev python3-setuptools python3-venv \
                             build-essential libssl-dev libffi-dev \
                             libgl1-mesa-dev libgles2-mesa-dev \
                             zlib1g-dev libncurses5-dev libsqlite3-dev \
                             libgdbm-dev libbz2-dev liblzma-dev

          pip install --user cython buildozer

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Build Tools and Platform
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;36.1.0" "platforms;android-33"

      - name: Set Android environment variables
        run: |
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.local/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/36.1.0" >> $GITHUB_ENV

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk
