name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Install Java 11 and Buildozer dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk python3-pip unzip git build-essential
          pip install --user cython buildozer

      # 3️⃣ Build APK with Buildozer (no Docker)
      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      # 4️⃣ Upload the APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: bin/*.apk
