name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build using the recommended action (wraps the official Buildozer docker image)
      - name: Build with Buildozer
        id: buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          # Your buildozer.spec is in repo root
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      # Upload the exact APK path returned by the action
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: faultcodes-apk
          path: ${{ steps.buildozer.outputs.filename }}

      # Optional: create a GitHub Release with the APK attached
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: ${{ steps.buildozer.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}